jobs:
  tests:
    name: testapp
    runs-on: ubuntu latest
      steps:
        -name: checkout repo
        uses: actions/checkout@v4
        -name: dependencies
        run: npm install
        -name: postgres
          uses: harmon758/postgresql-action@v1
          with:
            postgresql db: 'my_db'
            postgresql user: 'test_user'
            postgresql password: 'test_password'
        



